### ISSUE TITLE
xml文件、SQL链接 能否改成init方法初始化里

### ISSUE THREAD

**Issue by funny5258** [zhuxiujia/GoMybatis#1]
很高兴能够成为第一个forker、

xml文件、SQL链接 能否改成init方法初始化里

在程序的dao层直接执行方法呢

**Comment by zhuxiujia** [comment]
> 很高兴能够成为第一个forker、
> 
> xml文件、SQL链接 能否改成init方法初始化里
> 
> 在程序的dao层直接执行方法呢

可以的，推荐使用statikFS把一堆的mapper.xml打包成一个static.go文件里，然后在init方法里使用
<pre>
file, err := os.Open("/Example_ActivityMapper.xml")
bytes, _ := ioutil.ReadAll(file)
var exampleActivityMapperImpl ExampleActivityMapperImpl
//设置对应的mapper xml文件,因为bytes实际上就是xml的文本文件，这里也可以传[]byte(`...<select id="selectByCondition" resultMap="BaseResultMap">...`)
GoMybatis.UseProxyMapperByEngine(&exampleActivityMapperImpl, bytes, engine)
</pre>
这样就不需要管文件在服务器上的绝对路径了。github上文件系统的框架很多的.InfluxDB 中使用了 statik 这个工具将静态资源都编译进了二进制文件中。附上教程链接http://blog.fatedier.com/2016/08/01/compile-assets-into-binary-file-with-statik-in-golang/

**Comment by zhuxiujia** [comment]
> 很高兴能够成为第一个forker、
> 
> xml文件、SQL链接 能否改成init方法初始化里
> 
> 在程序的dao层直接执行方法呢

只需保证 GoMybatis.UseProxyMapperByEngine(&***）这个方法代理过你定义的struct的话，不管在什么地方使用都没关系，也不存在协程锁的问题（相当于根据xml中定义的sql规则给你的struct中包含的func写入了新的func）
