### ISSUE TITLE
请问NewSession是否能够提到类似Java的父类中？用隐式字段的方式。

### ISSUE THREAD

**Issue by onlysad** [zhuxiujia/GoMybatis#13]
类似如此
```
type BaseDao struct {
	NewSession func(config *GoMybatis.TransationRMClientConfig) (GoMybatis.Session, error)
}
```
```
type UserDao struct {
	BaseDao
	Insert func(user User) (int64, error)
	SelectById func(id int) (User, error) `mapperParams:"id"`
}

var session, err = userDao.NewSession(nil)
```

这样避免每一个Mapper都去定义一次NewSession，节省代码。
实际测试中发现 NewSession 并没有被注入代理方法。

阅读源码发现

```
if f.CanSet() {
	switch ft.Kind() {
	case reflect.Struct:
	case reflect.Func:
		if buildFunc != nil {
			buildRemoteMethod(f, ft, sf, buildFunc(sf))
		}
	}
}
```
GoMybatisProxy.go: 48行，case reflect.Struct里没有任何实现。

是暂未支持该功能，还是说有什么其他问题导致不可以这样做呢？
又或者有更好的实现方式？

多次打扰，真不好意思。

**Comment by zhuxiujia** [comment]
> 类似如此
> 
> ```
> type BaseDao struct {
> 	NewSession func(config *GoMybatis.TransationRMClientConfig) (GoMybatis.Session, error)
> }
> ```
> ```
> type UserDao struct {
> 	BaseDao
> 	Insert func(user User) (int64, error)
> 	SelectById func(id int) (User, error) `mapperParams:"id"`
> }
> 
> var session, err = userDao.NewSession(nil)
> ```
> 这样避免每一个Mapper都去定义一次NewSession，节省代码。
> 实际测试中发现 NewSession 并没有被注入代理方法。
> 
> 阅读源码发现
> 
> ```
> if f.CanSet() {
> 	switch ft.Kind() {
> 	case reflect.Struct:
> 	case reflect.Func:
> 		if buildFunc != nil {
> 			buildRemoteMethod(f, ft, sf, buildFunc(sf))
> 		}
> 	}
> }
> ```
> GoMybatisProxy.go: 48行，case reflect.Struct里没有任何实现。
> 
> 是暂未支持该功能，还是说有什么其他问题导致不可以这样做呢？
> 又或者有更好的实现方式？
> 
> 多次打扰，真不好意思。

NewSession      func() (GoMybatis.Session, error)方法主要是为了 能使session和自己的mapper文件强关联，以达到实现动态数据源 路由的功能。
你也可以使用SessionFactory new一个，但是得传入mapperName.
所以最简洁的办法是直接在mapper对象定义 NewSession      func() (GoMybatis.Session, error)
case reflect.Struct里没有任何实现 是因为mapper结构体 里面只支持动态写入func，而不是其他struct

**Comment by zhuxiujia** [comment]
> 类似如此
> 
> ```
> type BaseDao struct {
> 	NewSession func(config *GoMybatis.TransationRMClientConfig) (GoMybatis.Session, error)
> }
> ```
> ```
> type UserDao struct {
> 	BaseDao
> 	Insert func(user User) (int64, error)
> 	SelectById func(id int) (User, error) `mapperParams:"id"`
> }
> 
> var session, err = userDao.NewSession(nil)
> ```
> 这样避免每一个Mapper都去定义一次NewSession，节省代码。
> 实际测试中发现 NewSession 并没有被注入代理方法。
> 
> 阅读源码发现
> 
> ```
> if f.CanSet() {
> 	switch ft.Kind() {
> 	case reflect.Struct:
> 	case reflect.Func:
> 		if buildFunc != nil {
> 			buildRemoteMethod(f, ft, sf, buildFunc(sf))
> 		}
> 	}
> }
> ```
> GoMybatisProxy.go: 48行，case reflect.Struct里没有任何实现。
> 
> 是暂未支持该功能，还是说有什么其他问题导致不可以这样做呢？
> 又或者有更好的实现方式？
> 
> 多次打扰，真不好意思。

另外，“实际测试中发现 NewSession 并没有被注入代理方法。“是有写入的，可以参考Example_test.go中的实现，经测试是可以的

**Comment by onlysad** [comment]
> > 类似如此
> > ```
> > type BaseDao struct {
> > 	NewSession func(config *GoMybatis.TransationRMClientConfig) (GoMybatis.Session, error)
> > }
> > ```
> > ```
> > type UserDao struct {
> > 	BaseDao
> > 	Insert func(user User) (int64, error)
> > 	SelectById func(id int) (User, error) `mapperParams:"id"`
> > }
> > 
> > var session, err = userDao.NewSession(nil)
> > ```
> > 这样避免每一个Mapper都去定义一次NewSession，节省代码。
> > 实际测试中发现 NewSession 并没有被注入代理方法。
> > 阅读源码发现
> > ```
> > if f.CanSet() {
> > 	switch ft.Kind() {
> > 	case reflect.Struct:
> > 	case reflect.Func:
> > 		if buildFunc != nil {
> > 			buildRemoteMethod(f, ft, sf, buildFunc(sf))
> > 		}
> > 	}
> > }
> > ```
> > GoMybatisProxy.go: 48行，case reflect.Struct里没有任何实现。
> > 是暂未支持该功能，还是说有什么其他问题导致不可以这样做呢？
> > 又或者有更好的实现方式？
> > 多次打扰，真不好意思。
> 
> 另外，“实际测试中发现 NewSession 并没有被注入代理方法。“是有写入的，可以参考Example_test.go中的实现，经测试是可以的

NewSession写在Mapper里确实是可以的呀？ 您的意思是定义在Mapper里有写入，还是定义在隐式字段里有写入？

**Comment by zhuxiujia** [comment]
> > > 类似如此
> > > ```
> > > type BaseDao struct {
> > > 	NewSession func(config *GoMybatis.TransationRMClientConfig) (GoMybatis.Session, error)
> > > }
> > > ```
> > > ```
> > > type UserDao struct {
> > > 	BaseDao
> > > 	Insert func(user User) (int64, error)
> > > 	SelectById func(id int) (User, error) `mapperParams:"id"`
> > > }
> > > 
> > > var session, err = userDao.NewSession(nil)
> > > ```
> > > 这样避免每一个Mapper都去定义一次NewSession，节省代码。
> > > 实际测试中发现 NewSession 并没有被注入代理方法。
> > > 阅读源码发现
> > > ```
> > > if f.CanSet() {
> > > 	switch ft.Kind() {
> > > 	case reflect.Struct:
> > > 	case reflect.Func:
> > > 		if buildFunc != nil {
> > > 			buildRemoteMethod(f, ft, sf, buildFunc(sf))
> > > 		}
> > > 	}
> > > }
> > > ```
> > > GoMybatisProxy.go: 48行，case reflect.Struct里没有任何实现。
> > > 是暂未支持该功能，还是说有什么其他问题导致不可以这样做呢？
> > > 又或者有更好的实现方式？
> > > 多次打扰，真不好意思。
> > 
> > 
> > 另外，“实际测试中发现 NewSession 并没有被注入代理方法。“是有写入的，可以参考Example_test.go中的实现，经测试是可以的
> 
> NewSession写在Mapper里确实是可以的呀？ 您的意思是定义在Mapper里有写入，还是定义在隐式字段里有写入？

在go里，struct包含另外一个struct是组合而不是继承，有重复定义的风险，目前暂时不会使用这种办法。

**Comment by onlysad** [comment]
Java写了十年，有点小洁癖，大量类里出现一模一样的代码，总觉得难受 :P
明白了，我再想想看。

**Comment by zhuxiujia** [comment]
> Java写了十年，有点小洁癖，大量类里出现一模一样的代码，总觉得难受 :P
> 明白了，我再想想看。

是的，go和java不太一样，是不建议各种复杂的继承关系.后期可能会考虑接口做扩展成一个统一的NewSession接口

**Comment by onlysad** [comment]
感谢回复，期待更优化的版本。:P

**Comment by zhuxiujia** [comment]
> 类似如此
> 
> ```
> type BaseDao struct {
> 	NewSession func(config *GoMybatis.TransationRMClientConfig) (GoMybatis.Session, error)
> }
> ```
> ```
> type UserDao struct {
> 	BaseDao
> 	Insert func(user User) (int64, error)
> 	SelectById func(id int) (User, error) `mapperParams:"id"`
> }
> 
> var session, err = userDao.NewSession(nil)
> ```
> 这样避免每一个Mapper都去定义一次NewSession，节省代码。
> 实际测试中发现 NewSession 并没有被注入代理方法。
> 
> 阅读源码发现
> 
> ```
> if f.CanSet() {
> 	switch ft.Kind() {
> 	case reflect.Struct:
> 	case reflect.Func:
> 		if buildFunc != nil {
> 			buildRemoteMethod(f, ft, sf, buildFunc(sf))
> 		}
> 	}
> }
> ```
> GoMybatisProxy.go: 48行，case reflect.Struct里没有任何实现。
> 
> 是暂未支持该功能，还是说有什么其他问题导致不可以这样做呢？
> 又或者有更好的实现方式？
> 
> 多次打扰，真不好意思。

你好，已经在v4.8版本加入了 session的隐式实现，只需属性加一条GoMybatis.SessionSupport 即可使用

**Comment by onlysad** [comment]
噗。。。 不是说不打算这么做吗？ 这也太效率了吧。

**Comment by zhuxiujia** [comment]
> 噗。。。 不是说不打算这么做吗？ 这也太效率了吧。

这个实现比较简单，循环扫描即可，另外种实现方式估计还得研究研究。肯定没那么快

**Comment by onlysad** [comment]
```
type BaseDao struct {
	NewSession func(config *GoMybatis.TransationRMClientConfig) (GoMybatis.Session, error)
}
```

undefined: GoMybatis.TransationRMClientConfig 

TransationRMClientConfig咋没了？ 啥情况呀？

**Comment by zhuxiujia** [comment]
> ```
> type BaseDao struct {
> 	NewSession func(config *GoMybatis.TransationRMClientConfig) (GoMybatis.Session, error)
> }
> ```
> undefined: GoMybatis.TransationRMClientConfig
> 
> TransationRMClientConfig咋没了？ 啥情况呀？

TransationRM 整个模块新版本已经删了，后期会考虑使用改用rust（对等于c++）等 没有GC的语言做远程事务实现

**Comment by onlysad** [comment]
GoMybatis.SessionSupport 是加在Mapper的Struct属性里吗？

**Comment by zhuxiujia** [comment]
> GoMybatis.SessionSupport 是加在Mapper的Struct属性里吗？

是的，也可以在你自定义的 struct里，只要里面有包含 NewSession func() (GoMybatis.Session, error) 这个func就可以，类似的，其他方法也可以抽出来作为类似“父类“的概念作为公用
但是注意一点，包含的所有方法 所有者都是 最初调用engine.WriteMapperPtr（）的对象所有的，也就是说动态数据源的name取的默认是 最初那个对象的名字

**Comment by zhuxiujia** [comment]
> GoMybatis.SessionSupport 是加在Mapper的Struct属性里吗？

详细可以查看代码示例 https://github.com/zhuxiujia/GoMybatis/blob/master/example/Example_test.go

**Comment by onlysad** [comment]
```
if returnType == nil {
	panic("[GoMybatis] struct have no return values!")
}
```
GoMybatis.go: 64行， 这里抛出了异常。在添加了GoMybatis.SessionSupport之后。

```
type UserDao struct {
	//GoMybatis.SessionSupport
	Insert func(user User) (int64, error)
	SelectById func(id int) (User, error) `mapperParams:"id"`
}
```
我讲GoMybatis.SessionSupport注释之后就正常了。

请问是什么原因啊？

**Comment by onlysad** [comment]
> ```
> if returnType == nil {
> 	panic("[GoMybatis] struct have no return values!")
> }
> ```
> GoMybatis.go: 64行， 这里抛出了异常。在添加了GoMybatis.SessionSupport之后。
> 
> ```
> type UserDao struct {
> 	//GoMybatis.SessionSupport
> 	Insert func(user User) (int64, error)
> 	SelectById func(id int) (User, error) `mapperParams:"id"`
> }
> ```
> 我将GoMybatis.SessionSupport注释之后就正常了。
> 
> 请问是什么原因啊？

断点发现 funcName = NewSession ，returnType = nil

**Comment by zhuxiujia** [comment]
> ```
> if returnType == nil {
> 	panic("[GoMybatis] struct have no return values!")
> }
> ```
> GoMybatis.go: 64行， 这里抛出了异常。在添加了GoMybatis.SessionSupport之后。
> 
> ```
> type UserDao struct {
> 	//GoMybatis.SessionSupport
> 	Insert func(user User) (int64, error)
> 	SelectById func(id int) (User, error) `mapperParams:"id"`
> }
> ```
> 我讲GoMybatis.SessionSupport注释之后就正常了。
> 
> 请问是什么原因啊？

是最新4.8版本？Example_test.go 里面SessionSupport测试是正常的

**Comment by onlysad** [comment]
我是将GoMybatis包和pkg删除后，重新go get下载的，这样获取到的是最新的吗？
才开始学go，不是很清楚。

> > ```
> > if returnType == nil {
> > 	panic("[GoMybatis] struct have no return values!")
> > }
> > ```
> > GoMybatis.go: 64行， 这里抛出了异常。在添加了GoMybatis.SessionSupport之后。
> > ```
> > type UserDao struct {
> > 	//GoMybatis.SessionSupport
> > 	Insert func(user User) (int64, error)
> > 	SelectById func(id int) (User, error) `mapperParams:"id"`
> > }
> > ```
> > 我讲GoMybatis.SessionSupport注释之后就正常了。
> > 请问是什么原因啊？
> 
> 是最新4.8版本？Example_test.go 里面SessionSupport测试是正常的

我是将GoMybatis包和pkg删除后，重新go get下载的，这样获取到的是最新的吗？
才开始学go，不是很清楚。

**Comment by onlysad** [comment]
> 我是将GoMybatis包和pkg删除后，重新go get下载的，这样获取到的是最新的吗？
> 才开始学go，不是很清楚。
> 
> > > ```
> > > if returnType == nil {
> > > 	panic("[GoMybatis] struct have no return values!")
> > > }
> > > ```
> > > GoMybatis.go: 64行， 这里抛出了异常。在添加了GoMybatis.SessionSupport之后。
> > > ```
> > > type UserDao struct {
> > > 	//GoMybatis.SessionSupport
> > > 	Insert func(user User) (int64, error)
> > > 	SelectById func(id int) (User, error) `mapperParams:"id"`
> > > }
> > > ```
> > > 我讲GoMybatis.SessionSupport注释之后就正常了。
> > > 请问是什么原因啊？
> > 
> > 
> > 是最新4.8版本？Example_test.go 里面SessionSupport测试是正常的
> 
> 我是将GoMybatis包和pkg删除后，重新go get下载的，这样获取到的是最新的吗？
> 才开始学go，不是很清楚。

应该是最新的呀，我检查了备份的历史版本里没有GoMybatis.SessionSupport

**Comment by zhuxiujia** [comment]
> 我是将GoMybatis包和pkg删除后，重新go get下载的，这样获取到的是最新的吗？
> 才开始学go，不是很清楚。
> 
> > > ```
> > > if returnType == nil {
> > > 	panic("[GoMybatis] struct have no return values!")
> > > }
> > > ```
> > > GoMybatis.go: 64行， 这里抛出了异常。在添加了GoMybatis.SessionSupport之后。
> > > ```
> > > type UserDao struct {
> > > 	//GoMybatis.SessionSupport
> > > 	Insert func(user User) (int64, error)
> > > 	SelectById func(id int) (User, error) `mapperParams:"id"`
> > > }
> > > ```
> > > 我讲GoMybatis.SessionSupport注释之后就正常了。
> > > 请问是什么原因啊？
> > 
> > 
> > 是最新4.8版本？Example_test.go 里面SessionSupport测试是正常的
> 
> 我是将GoMybatis包和pkg删除后，重新go get下载的，这样获取到的是最新的吗？
> 才开始学go，不是很清楚。

贴代码看看

**Comment by zhuxiujia** [comment]
> > 我是将GoMybatis包和pkg删除后，重新go get下载的，这样获取到的是最新的吗？
> > 才开始学go，不是很清楚。
> > > > ```
> > > > if returnType == nil {
> > > > 	panic("[GoMybatis] struct have no return values!")
> > > > }
> > > > ```
> > > > GoMybatis.go: 64行， 这里抛出了异常。在添加了GoMybatis.SessionSupport之后。
> > > > ```
> > > > type UserDao struct {
> > > > 	//GoMybatis.SessionSupport
> > > > 	Insert func(user User) (int64, error)
> > > > 	SelectById func(id int) (User, error) `mapperParams:"id"`
> > > > }
> > > > ```
> > > > 我讲GoMybatis.SessionSupport注释之后就正常了。
> > > > 请问是什么原因啊？
> > > 
> > > 
> > > 是最新4.8版本？Example_test.go 里面SessionSupport测试是正常的
> > 
> > 
> > 我是将GoMybatis包和pkg删除后，重新go get下载的，这样获取到的是最新的吗？
> > 才开始学go，不是很清楚。
> 
> 应该是最新的呀，我检查了备份的历史版本里没有GoMybatis.SessionSupport

```
//本地事务使用例子
func Test_local_Transation(t *testing.T) {
	if MysqlUri == "" || MysqlUri == "*" {
		fmt.Println("no database url define in MysqlConfig.go , you must set the mysql link!")
		return
	}
	//使用事务
	var session, err = exampleActivityMapper.SessionSupport.NewSession()
	if err != nil {
		t.Fatal(err)
	}
	session.Begin() //开启事务
	var activityBean = Activity{
		Id:   "170",
		Name: "rs168-8",
	}
	var updateNum, e = exampleActivityMapper.UpdateById(&session, activityBean) //sessionId 有值则使用已经创建的session，否则新建一个session
	fmt.Println("updateNum=", updateNum)
	if e != nil {
		panic(e)
	}
	session.Commit() //提交事务
	session.Close()  //关闭事务
}

//=== RUN   Test_local_Transation
//2019/04/13 20:31:55 [GoMybatis] [2019-04-13T20:31:55.113014+08:00] Preparing sql ==>  update //biz_activity  set  name = 'rs168-8',  pc_link = '',  h5_link = '',  remark = '',  create_time = '0001-01-01 //00:00:00',  delete_flag = 0  where id = '170' and delete_flag = 1
//updateNum= 0
//--- PASS: Test_local_Transation (0.03s)
//PASS

```
example.go里是执行成功的

**Comment by onlysad** [comment]
<img width="499" alt="QQ20190413-203202@2x" src="https://user-images.githubusercontent.com/6871973/56079770-3c502200-5e2b-11e9-8ed2-2367e4ab11e1.png">
```
func GetUserDao() UserDao{
	conn := utils.DBConnUtil{}.GetConn()
	conn.Engine.WriteMapperPtr(&userDao, bytes)
	return userDao
}
```
bytes确认不是为nil，有获取到xml

```
type UserDao struct {
	GoMybatis.SessionSupport
	Insert func(user User) (int64, error)
	SelectById func(id int) (User, error) `mapperParams:"id"`
}
```
而且注释掉GoMybatis.SessionSupport就可以正常运行，其他我都没改过呀。

**Comment by zhuxiujia** [comment]
> <img alt="QQ20190413-203202@2x" width="499" src="https://user-images.githubusercontent.com/6871973/56079770-3c502200-5e2b-11e9-8ed2-2367e4ab11e1.png">
> 
> ```
> func GetUserDao() UserDao{
> 	conn := utils.DBConnUtil{}.GetConn()
> 	conn.Engine.WriteMapperPtr(&userDao, bytes)
> 	return userDao
> }
> ```
> bytes确认不是为nil，有获取到xml
> 
> ```
> type UserDao struct {
> 	GoMybatis.SessionSupport
> 	Insert func(user User) (int64, error)
> 	SelectById func(id int) (User, error) `mapperParams:"id"`
> }
> ```
> 而且注释掉GoMybatis.SessionSupport就可以正常运行，其他我都没改过呀。

那例子  里的代码  你能跑通不？我这边试了是可以跑通的

**Comment by onlysad** [comment]
type ExampleActivityMapper struct 中
NewSession func() (GoMybatis.Session, error)
把session事务操作.写法2 注释掉执行test 跟我报一样的错。。。。

> > <img alt="QQ20190413-203202@2x" width="499" src="https://user-images.githubusercontent.com/6871973/56079770-3c502200-5e2b-11e9-8ed2-2367e4ab11e1.png">
> > ```
> > func GetUserDao() UserDao{
> > 	conn := utils.DBConnUtil{}.GetConn()
> > 	conn.Engine.WriteMapperPtr(&userDao, bytes)
> > 	return userDao
> > }
> > ```
> > bytes确认不是为nil，有获取到xml
> > ```
> > type UserDao struct {
> > 	GoMybatis.SessionSupport
> > 	Insert func(user User) (int64, error)
> > 	SelectById func(id int) (User, error) `mapperParams:"id"`
> > }
> > ```
> > 而且注释掉GoMybatis.SessionSupport就可以正常运行，其他我都没改过呀。
> 
> 那例子 里的代码 你能跑通不？我这边试了是可以跑通的

type ExampleActivityMapper struct 中
NewSession func() (GoMybatis.Session, error)
把session事务操作.写法2 注释掉执行test 跟我报一样的错。。。。
不注释掉则正常。

**Comment by onlysad** [comment]
```
func GetUserDao() *UserDao{
	once.Do(func() {
		this = &UserDao{}
		var bytes, _ = ioutil.ReadFile("src/dao/UserDao.xml")
		engineUtil.Engine.WriteMapperPtr(this, bytes)
		fmt.Println("****************************", "单例完成")
	})
	engineUtil.Open()
	return this
}
```
确认Bug已修复，单例模式也改出来了，没有问题。
![image](https://user-images.githubusercontent.com/6871973/56081534-0453d980-5e41-11e9-81e6-bdc7f3803db9.png)
从日志上看到，多次访问，单例完成只输出了一次，完美。

**Comment by onlysad** [comment]
感谢支持 💯
