### ISSUE TITLE
有对应的生成mapper文件和struct文件的代码么？谢谢

### ISSUE THREAD

**Issue by sinxsoft** [zhuxiujia/GoMybatis#14]
表比较多，手写比较费力且容易出错。

**Comment by onlysad** [comment]
哈哈，一看就是MyBatis Generator过来的。
目前估计只能自己拿MyBatis Generator来改，我之前想过，不过暂时没时间动手，改动量应该不大。
主要就是拿掉几个GoMybatis不支持的标签，以及langType的对应调整。
你也可以就用MyBatis Generator来生成XML，只要保证你XML的dtd文件是生效的，哪些是不支持的属性和标签都一目了然，手动删除就好了，也比自己从头手写快得多。

**Comment by zhuxiujia** [comment]
> 表比较多，手写比较费力且容易出错。

工作量巨大，一个人搞不完。。。。

**Comment by onlysad** [comment]
> > 表比较多，手写比较费力且容易出错。
> 
> 工作量巨大，一个人搞不完。。。。

NewSession的问题确认了吗？

**Comment by onlysad** [comment]
> > 表比较多，手写比较费力且容易出错。
> 
> 工作量巨大，一个人搞不完。。。。

基于MyBatis Generator来改，工作量应该是不大的。

**Comment by zhuxiujia** [comment]
> 表比较多，手写比较费力且容易出错。

以前做的插件，不过是基于idea的java版的，有空给它改成go版的 https://github.com/zhuxiujia/IdeaEasyPlugin

**Comment by zhuxiujia** [comment]
> > > 表比较多，手写比较费力且容易出错。
> > 
> > 
> > 工作量巨大，一个人搞不完。。。。
> 
> NewSession的问题确认了吗？

估计是你本地有问题，你本地还需要检查下，测试是跑通的。到来你那边没有通

**Comment by onlysad** [comment]
> > > > 表比较多，手写比较费力且容易出错。
> > > 
> > > 
> > > 工作量巨大，一个人搞不完。。。。
> > 
> > 
> > NewSession的问题确认了吗？
> 
> 估计是你本地有问题，你本地还需要检查下，测试是跑通的。到来你那边没有通

你看了我最新的回复吗？测试也有问题的。

**Comment by zhuxiujia** [comment]
> 哈哈，一看就是MyBatis Generator过来的。
> 目前估计只能自己拿MyBatis Generator来改，我之前想过，不过暂时没时间动手，改动量应该不大。
> 主要就是拿掉几个GoMybatis不支持的标签，以及langType的对应调整。
> 你也可以就用MyBatis Generator来生成XML，只要保证你XML的dtd文件是生效的，哪些是不支持的属性和标签都一目了然，手动删除就好了，也比自己从头手写快得多。

是的，除了langType，那一块改，其他基本不用大动。基本上是兼容的

**Comment by onlysad** [comment]
> > 哈哈，一看就是MyBatis Generator过来的。
> > 目前估计只能自己拿MyBatis Generator来改，我之前想过，不过暂时没时间动手，改动量应该不大。
> > 主要就是拿掉几个GoMybatis不支持的标签，以及langType的对应调整。
> > 你也可以就用MyBatis Generator来生成XML，只要保证你XML的dtd文件是生效的，哪些是不支持的属性和标签都一目了然，手动删除就好了，也比自己从头手写快得多。
> 
> 是的，除了langType，那一块改，其他基本不用大动。基本上是兼容的

麻烦看一下那边我最新的回复，测试样例注释掉非隐式的NewSession就会触发跟我本地一样的BUG。

**Comment by zhuxiujia** [comment]
> > > 哈哈，一看就是MyBatis Generator过来的。
> > > 目前估计只能自己拿MyBatis Generator来改，我之前想过，不过暂时没时间动手，改动量应该不大。
> > > 主要就是拿掉几个GoMybatis不支持的标签，以及langType的对应调整。
> > > 你也可以就用MyBatis Generator来生成XML，只要保证你XML的dtd文件是生效的，哪些是不支持的属性和标签都一目了然，手动删除就好了，也比自己从头手写快得多。
> > 
> > 
> > 是的，除了langType，那一块改，其他基本不用大动。基本上是兼容的
> 
> 麻烦看一下那边我最新的回复，测试样例注释掉非隐式的NewSession就会触发跟我本地一样的BUG。

这个bug新版本修复了 更新看看

**Comment by onlysad** [comment]
这么快，666.
我正在弄东西，代码改乱了，一会儿测试。
我想把
```
GoMybatis.GoMybatisEngine{}.New()
var bytes, _ = ioutil.ReadFile("src/dao/UserDao.xml")
Engine.WriteMapperPtr(&userDao, bytes)
```
这一块儿代码优化成单例模式，仅仅项目启动时执行一次，避免每次调用数据库都执行一次浪费性能。
在操作数据库时，只做Engine.Open

我这要做在GoMybatis底层是允许的吗？

**Comment by zhuxiujia** [comment]
> > > > > 哈哈，一看就是MyBatis Generator过来的。
> > > > > 目前估计只能自己拿MyBatis Generator来改，我之前想过，不过暂时没时间动手，改动量应该不大。
> > > > > 主要就是拿掉几个GoMybatis不支持的标签，以及langType的对应调整。
> > > > > 你也可以就用MyBatis Generator来生成XML，只要保证你XML的dtd文件是生效的，哪些是不支持的属性和标签都一目了然，手动删除就好了，也比自己从头手写快得多。
> > > > 
> > > > 
> > > > 是的，除了langType，那一块改，其他基本不用大动。基本上是兼容的
> > > 
> > > 
> > > 麻烦看一下那边我最新的回复，测试样例注释掉非隐式的NewSession就会触发跟我本地一样的BUG。
> > 
> > 
> > 这个bug新版本修复了 更新看看
> 
> 这么快，666.
> 我正在弄东西，代码改乱了，一会儿测试。
> 我想把
> 
> ```
> GoMybatis.GoMybatisEngine{}.New()
> var bytes, _ = ioutil.ReadFile("src/dao/UserDao.xml")
> Engine.WriteMapperPtr(&userDao, bytes)
> ```
> 这一块儿代码优化成单例模式，仅仅项目启动时执行一次，避免每次调用数据库都执行一次浪费性能。
> 在操作数据库时，只做Engine.Open
> 
> 我这样做在GoMybatis底层是允许的吗？

engine本身可以是单例的，Engine.WriteMapperPtr(&userDao, bytes)也应该只在程序初始化只调用一次

**Comment by sinxsoft** [comment]
那我就自己写一个

**Comment by zhuxiujia** [comment]
> 表比较多，手写比较费力且容易出错。

最新版本增加了内置生成xml文件的办法.
