### ISSUE TITLE
传入入一个有int字段的struct到查询方法，int=22变成了26.

### ISSUE THREAD

**Issue by sinxsoft** [zhuxiujia/GoMybatis#16]
func main() {
	arg := 22
	ConvertTest(arg)
}

func ConvertTest(arg interface{}) {
	fmt.Println(strconv.FormatInt(int64(arg.(int)), 8)) //截取了下述方法：
}

==============================
func caseType(arg interface{}, types reflect.Type) string {
	switch types.Kind() {
	case reflect.String:
		return arg.(string)
	case reflect.Int:
		return strconv.FormatInt(int64(arg.(int)), 8)
	case reflect.Int8:
		return strconv.FormatInt(int64(arg.(int8)), 8)
	case reflect.Int16:
		return strconv.FormatInt(int64(arg.(int16)), 16)
	case reflect.Int32:
		return strconv.FormatInt(int64(arg.(int32)), 32)
	case reflect.Int64:
		return strconv.FormatInt(int64(arg.(int64)), 64)
	case reflect.Float32:
		return strconv.FormatFloat(float64(arg.(float32)), 'f', -1, 32)
	case reflect.Float64:
		return strconv.FormatFloat(float64(arg.(float64)), 'f', -1, 64)
	case reflect.Bool:
		return strconv.FormatBool(arg.(bool))
	case reflect.Uint:
		return strconv.FormatUint(uint64(arg.(uint)), 2)
	case reflect.Uint8:
		return strconv.FormatUint(uint64(arg.(uint8)), 8)
	case reflect.Uint16:
		return strconv.FormatUint(uint64(arg.(uint16)), 16)
	case reflect.Uint32:
		return strconv.FormatUint(uint64(arg.(uint32)), 32)
	case reflect.Uint64:
		return strconv.FormatUint(uint64(arg.(uint64)), 64)
	case reflect.Struct:
		if types.String() == "time.Time" {
			return arg.(time.Time).Format(`2006-01-02 15:04:05`)
		} else {
			return fmt.Sprint(arg)
		}
	default:
		return fmt.Sprint(arg)
	}
	return fmt.Sprint(arg)
}

**Comment by sinxsoft** [comment]
这句话出了问题：strconv.FormatInt(int64(arg.(int)), 8)

**Comment by zhuxiujia** [comment]
> 这句话出了问题：strconv.FormatInt(int64(arg.(int)), 8)

是的，已经修复了这个bug
