### ISSUE TITLE
线程安全问题

### ISSUE THREAD

**Issue by zhaobingss** [zhuxiujia/GoMybatis#17]
这里建议改用线程安全的sync.Map
涉及文件：
SessionFactory.go
SessionFactorySession.go
![image](https://user-images.githubusercontent.com/14836112/56563805-37376380-65df-11e9-97b4-cac493857096.png)

**Comment by zhuxiujia** [comment]
> 这里建议改用线程安全的sync.Map
> 涉及文件：
> SessionFactory.go
> SessionFactorySession.go
> ![image](https://user-images.githubusercontent.com/14836112/56563805-37376380-65df-11e9-97b4-cac493857096.png)

已修改，感谢提醒
