### ISSUE TITLE
Oracle下，无法查询返回空对象

### ISSUE THREAD

**Issue by loraxh** [zhuxiujia/GoMybatis#18]
这个很不错，就是缺乏完善文档，希望建群促进交流

**Comment by loraxh** [comment]
使用_ "github.com/wendal/go-oci8"驱动

日志返回
2019/05/22 22:31:56 [GoMybatis] [8c6e1043-d5a9-4d44-9db0-9c0c5e031f5e] Query ==>   select * from TUsers where 1=1 and names = 'test'  
2019/05/22 22:31:57 [GoMybatis] [8c6e1043-d5a9-4d44-9db0-9c0c5e031f5e] Close session
2019/05/22 22:31:57 [GoMybatis] [8c6e1043-d5a9-4d44-9db0-9c0c5e031f5e] ReturnRows <== 2
result= [{"id":0,"serialno":"","names":"","pinyin":"","gender":"","password":"","birthdate":"","profession":"","headpicurl":"","Introduction":"","mobile":"","marks":"","syscode":"","Sortid":0,"enables":0}]

**Comment by zhuxiujia** [comment]
> 使用_ "github.com/wendal/go-oci8"驱动
> 
> 日志返回
> 2019/05/22 22:31:56 [GoMybatis] [8c6e1043-d5a9-4d44-9db0-9c0c5e031f5e] Query ==> select * from TUsers where 1=1 and names = 'test'
> 2019/05/22 22:31:57 [GoMybatis] [8c6e1043-d5a9-4d44-9db0-9c0c5e031f5e] Close session
> 2019/05/22 22:31:57 [GoMybatis] [8c6e1043-d5a9-4d44-9db0-9c0c5e031f5e] ReturnRows <== 2
> result= [{"id":0,"serialno":"","names":"","pinyin":"","gender":"","password":"","birthdate":"","profession":"","headpicurl":"","Introduction":"","mobile":"","marks":"","syscode":"","Sortid":0,"enables":0}]

oracle 安装c/c++编译了吗
Install Oracle full client or Instant Client:

https://www.oracle.com/technetwork/database/database-technologies/instant-client/downloads/index.html

Install a C/C++ compiler

Install pkg-config, edit your package config file oci8.pc (examples below), then set environment variable PKG_CONFIG_PATH to oci8.pc file location (Or can use Go tag noPkgConfig then setup environment variables CGO_CFLAGS and CGO_LDFLAGS)

**Comment by zhuxiujia** [comment]
> 使用_ "github.com/wendal/go-oci8"驱动
> 
> 日志返回
> 2019/05/22 22:31:56 [GoMybatis] [8c6e1043-d5a9-4d44-9db0-9c0c5e031f5e] Query ==> select * from TUsers where 1=1 and names = 'test'
> 2019/05/22 22:31:57 [GoMybatis] [8c6e1043-d5a9-4d44-9db0-9c0c5e031f5e] Close session
> 2019/05/22 22:31:57 [GoMybatis] [8c6e1043-d5a9-4d44-9db0-9c0c5e031f5e] ReturnRows <== 2
> result= [{"id":0,"serialno":"","names":"","pinyin":"","gender":"","password":"","birthdate":"","profession":"","headpicurl":"","Introduction":"","mobile":"","marks":"","syscode":"","Sortid":0,"enables":0}]

理论上说，框架和驱动的桥接是通过 go标准款 database/sql来交互的，如果它这个驱动能在标准库下跑，就能在gomybatis下执行

**Comment by zhuxiujia** [comment]
> 这个很不错，就是缺乏完善文档，希望建群促进交流

微信群的话，需要满足至少4个人以上的

**Comment by loraxh** [comment]
使用 database/sql是可以正常查询出来，我在GoMybatis单元381行打了个日志
      var b, _ = json.Marshal(res)
     println("result=", string(b))

这里打印的日志为result= [{"BIRTHDATE":"MTk4OTEyMQ==","ENABLES":"MQ==","GENDER":"MQ==","HEADPIC":"5ZOI5ZOI","ID":"MQ==","INTRODUCTION":"5L2g5aW9","MARKS":"5rWL6K+V",......
似乎也不能正常显示，应该是哪里需要设置

**Comment by zhuxiujia** [comment]
> 使用 database/sql是可以正常查询出来，我在GoMybatis单元381行打了个日志
> var b, _ = json.Marshal(res)
> println("result=", string(b))
> 
> 这里打印的日志为result= [{"BIRTHDATE":"MTk4OTEyMQ==","ENABLES":"MQ==","GENDER":"MQ==","HEADPIC":"5ZOI5ZOI","ID":"MQ==","INTRODUCTION":"5L2g5aW9","MARKS":"5rWL6K+V",......
> 似乎也不能正常显示，应该是哪里需要设置

能确定驱动载入成功了吗？

**Comment by loraxh** [comment]
调试了下发现是大小写问题，oralce默认返回的字段名称是大写，在单元GoMybatisSqlResultDecoder.go中方法sqlStructConvert，将对象与数据集匹配是默认的是小写，这导致匹配失败，返回数据集为空
   我将52行代码  
           var repleaceName = tItemTypeFieldType.Name
  改为
         var repleaceName = strings.ToUpper(tItemTypeFieldType.Name)
成功返回结果

**Comment by zhuxiujia** [comment]
> 调试了下发现是大小写问题，oralce默认返回的字段名称是大写，在单元GoMybatisSqlResultDecoder.go中方法sqlStructConvert，将对象与数据集匹配是默认的是小写，这导致匹配失败，返回数据集为空
> 我将52行代码
> var repleaceName = tItemTypeFieldType.Name
> 改为
> var repleaceName = strings.ToUpper(tItemTypeFieldType.Name)
> 成功返回结果

oralce 返回的字段好奇葩呀，你这种情况有变通的办法，GoMybatis 第一步是根据结构体field 匹配，如果匹配不到 则 取json tag匹配，感觉你这情况，建议吧结构体 改成全大写，但是json tag是小写。
