### ISSUE TITLE
你好，请问这个支持collection标签吗

### ISSUE THREAD

**Issue by wujincheng2333** [zhuxiujia/GoMybatis#19]
类似mybtais的一对一和一对多的查询

**Comment by zhuxiujia** [comment]
> 类似mybtais的一对一和一对多的查询

请仔细看文档，支持，集合目前支持go的slice，array，map。

**Comment by wujincheng2333** [comment]
我看了，示例都是单表操作，有没有resultMap 一对多或一对一的查询使用示例

**Comment by anjieych** [comment]
从源码来看，应该是支持；但是多表查询必须手写<select> 也就是说不能用<selectTemplete>来“偷懒".
