### ISSUE TITLE
installation doesn't suppport go mod.

### ISSUE THREAD

**Issue by focusonline** [zhuxiujia/GoMybatis#23]
Hi Zhuxiujia,
   I add reference of gomybatis like the instruction, 
_ "github.com/go-sql-driver/mysql" //Mysql驱动程序，必须使用 _ 下划线导入
 github.com/zhuxiujia/GoMybatis"
 and run go mod tidy, it tells me the error as below:
    ---> go mod tidy
     go: finding github.com/zhuxiujia/GoMybatis/lib/github.com/google/uuid latest
     go: github.com/zhuxiujia/GoMybatis/lib/github.com/google/uuid@v0.0.0-20190725080449-
     7e339b0e19b9: parsing go.mod: unexpected module path "github.com/google/uuid"
      go: error loading module requirements
obviously, it can not find the dependency packages google/uuid, because you did not organize them by go mod mode.
     If i install the package by command, 
     --->go get github.com/zhuxiujia/GoMybatis
    it returns same error and fail in finding dependency. 
     could you please fix it?

**Comment by zhuxiujia** [comment]
> Hi Zhuxiujia,
> I add reference of gomybatis like the instruction,
> _ "github.com/go-sql-driver/mysql" //Mysql驱动程序，必须使用 _ 下划线导入
> github.com/zhuxiujia/GoMybatis"
> and run go mod tidy, it tells me the error as below:
> ---> go mod tidy
> go: finding github.com/zhuxiujia/GoMybatis/lib/github.com/google/uuid latest
> go: github.com/zhuxiujia/GoMybatis/lib/github.com/google/uuid@v0.0.0-20190725080449-
> [7e339b0](https://github.com/zhuxiujia/GoMybatis/commit/7e339b0e19b998313e03e42cf45e407c023375c3): parsing go.mod: unexpected module path "github.com/google/uuid"
> go: error loading module requirements
> obviously, it can not find the dependency packages google/uuid, because you did not organize them by go mod mode.
> If i install the package by command,
> --->go get github.com/zhuxiujia/GoMybatis
> it returns same error and fail in finding dependency.
> could you please fix it?

fixed, try  update project and try again run  go mod tidy

**Comment by focusonline** [comment]
dear, 
I tried again.
but it doesn't work yet.
same errro is returned.
--->go get -u github.com/zhuxiujia/GoMybatis
go: finding github.com/zhuxiujia/GoMybatis/lib/github.com/google/uuid latest
go: github.com/zhuxiujia/GoMybatis/lib/github.com/google/uuid@v0.0.0-20190725080449-7e339b0e19b9: parsing go.mod: unexpected module path "github.com/google/uuid"
go: error loading module requirements
-------
I do appreciate your effort, but seems this time, luck is not on our side.

**Comment by zhuxiujia** [comment]
> ## dear,
> I tried again.
> but it doesn't work yet.
> same errro is returned.
> --->go get -u github.com/zhuxiujia/GoMybatis
> go: finding github.com/zhuxiujia/GoMybatis/lib/github.com/google/uuid latest
> go: github.com/zhuxiujia/GoMybatis/lib/github.com/google/uuid@v0.0.0-20190725080449-7e339b0e19b9: parsing go.mod: unexpected module path "github.com/google/uuid"
> go: error loading module requirements
> I do appreciate your effort, but seems this time, luck is not on our side.

I suggest you use vendor or govendor    first.
if use mod, we must add all  of driver mod in project. like  mysql,pg,sqlite driver,
and Mod will be supported soon

**Comment by focusonline** [comment]
okay, I will try the primitive vendor mode, remove go mod temporarily.
I do like this go mybatis implemention, eager to try it.
let me test and feedback you soon.
thank you for such awesome contribution. I wish it will be the top boss that domains the ORM of go.
anyway, if it supported the go mod architecture, please let me know. I will follow this project.

**Comment by kyuuube** [comment]
please support go mod . I will follow this project too.

**Comment by zhuxiujia** [comment]
the new version is support go.mod,  please use
```mod
//go.mod加入依赖
require (
	github.com/go-sql-driver/mysql v1.5.0
	github.com/zhuxiujia/GoMybatis v6.1.6+incompatible
)
```
