### ISSUE TITLE
不支持 go module吗,还是我打开方式不对

### ISSUE THREAD

**Issue by BoomManPro** [zhuxiujia/GoMybatis#26]

**Comment by dlhf** [comment]
我也想问问，这个代码来下来怎么整

**Comment by BoomManPro** [comment]
> 我也想问问，这个代码来下来怎么整

Example 使用go path方式倒是可以运行

**Comment by zhuxiujia** [comment]
> 我也想问问，这个代码来下来怎么整

看example里面readme.md有安装教程，暂时只支持go path运行方式，很快会支持go mod

**Comment by zhuxiujia** [comment]
> 我也想问问，这个代码来下来怎么整

另外附上使用文档：  https://zhuxiujia.github.io/gomybatis.io/#/getting-started

**Comment by zhuxiujia** [comment]
> 我也想问问，这个代码来下来怎么整

新版本已支持go.mod

**Comment by zhuxiujia** [comment]
> _No description provided._

新版本已支持go.mod
