### ISSUE TITLE
请问一下包拉不下来是是什么问题呢？

### ISSUE THREAD

**Issue by huanpython** [zhuxiujia/GoMybatis#28]
package github.com/zhuxiujia/GoMybatis: cannot download, $GOPATH must not be set to $GOROOT. For more details see: 'go help gopath'

goland一直报这个错

**Comment by zhuxiujia** [comment]
> package github.com/zhuxiujia/GoMybatis: cannot download, $GOPATH must not be set to $GOROOT. For more details see: 'go help gopath'
> 
> goland一直报这个错

你这个是 gopath goroot设置问题，和本框架没有关系。建议看卡博客论坛，装好环境
