### ISSUE TITLE
项目中的example中SelectByIds 方法好像有问题      

### ISSUE THREAD

**Issue by Arvinxiaoxu** [zhuxiujia/GoMybatis#3]
<select id="SelectByIds" >
        select id,name,age
        from tb_user
        where id in
        <foreach collection="ids" item="item" index="index"   open="(" close=")" >
            #{item}
        </foreach>
    </select>
发送的sql语句，select id,name,age        from tb_user        where id in ( 1 2)，我传递的是
ids := []int{1,2},而ids的打印结果是[1 2]，好像separator没有排上用场

**Comment by zhuxiujia** [comment]
> select id,name,age from tb_user where id in #{item} 发送的sql语句，select id,name,age from tb_user where id in ( 1 2)，我传递的是 ids := []int{1,2},而ids的打印结果是[1 2]，好像separator没有排上用场

已修复separator没有插入的问题，更新一下看看

**Comment by Arvinxiaoxu** [comment]
> > select id,name,age from tb_user where id in #{item} 发送的sql语句，select id,name,age from tb_user where id in ( 1 2)，我传递的是 ids := []int{1,2},而ids的打印结果是[1 2]，好像separator没有排上用场
> 
> 已修复separator没有插入的问题，更新一下看看

可以了大哥，杠杠的
