### ISSUE TITLE
照着示例写结果运行不了

### ISSUE THREAD

**Issue by rxrddd** [zhuxiujia/GoMybatis#34]
panic: runtime error: invalid memory address or nil pointer dereference
`func init() {
	if MysqlUri == "*" {
		println("GoMybatisEngine not init! because MysqlUri is * or MysqlUri is ''")
		return
	}
	engine = GoMybatis.GoMybatisEngine{}.New()

	//mysql链接格式为         用户名:密码@(数据库链接地址:端口)/数据库名称   例如root:123456@(***.mysql.rds.aliyuncs.com:3306)/test
	_, err := engine.Open("mysql", MysqlUri) //此处请按格式填写你的mysql链接，这里用*号代替
	if err != nil {
		panic(err.Error())
	}
	//读取mapper xml文件
	bytes, _ := ioutil.ReadFile("Example_ActivityMapper.xml")
	//设置对应的mapper xml文件
	engine.WriteMapperPtr(&exampleActivityMapper, bytes) 这一步报错
}
 `

**Comment by zhuxiujia** [comment]
报错信息看看
