### ISSUE TITLE
非空的判断逻辑

### ISSUE THREAD

**Issue by guotie** [zhuxiujia/GoMybatis#35]
我看sql对于一个字符串是否非空的判断就是判断这个参入的指针是否为空，但如果一个string的值为""的话，还是会执行。

这样虽然也没有问题，但是用起来很不方便，建议对于字符串的非空判断改成字符串不为nil，且字符串不为""

**Comment by guotie** [comment]
或者启用一个关键字来判断string是否为空，例如empty

**Comment by zhuxiujia** [comment]
> 我看sql对于一个字符串是否非空的判断就是判断这个参入的指针是否为空，但如果一个string的值为""的话，还是会执行。
> 
> 这样虽然也没有问题，但是用起来很不方便，建议对于字符串的非空判断改成字符串不为nil，且字符串不为""

参数是字符串当然判断 ！=“”，如果参数是字符串指针  比如 *string ，那么可以写成   ！= nil ，即判断是否空指针

**Comment by guotie** [comment]
..........
