### ISSUE TITLE
直接使用mapper查询无法映射，需要手动增加resultMap

### ISSUE THREAD

**Issue by wzhsh90** [zhuxiujia/GoMybatis#38]
一、type Activity struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
  <select id="SelectAll" >
        select * from users
    </select>
 exampleActivityMapperImpl.SelectAll()
修改为:
  <select id="SelectAll" resultMap="BaseResultMap">
        select * from users
    </select>

    <resultMap id="BaseResultMap" tables="users">
        <result column="id" property="Id" />
        <result column="name" property="Name"/>
    </resultMap>
或者 select id as Id,name as Name from users 才行

二、模板标签默认指向于resultMap标签（resultMap="BaseResultMap"），因此先定义resultMap标签
这个有问题，也必须手动加上 resultMap="BaseResultMap" 才行

**Comment by zhuxiujia** [comment]
> 一、type Activity struct {
> Id string `json:"id"`
> Name string `json:"name"`
> }
> select * from users
> exampleActivityMapperImpl.SelectAll()
> 修改为:
> select * from users
> 
> ```
> <resultMap id="BaseResultMap" tables="users">
>     <result column="id" property="Id" />
>     <result column="name" property="Name"/>
> </resultMap>
> ```
> 
> 或者 select id as Id,name as Name from users 才行
> 
> 二、模板标签默认指向于resultMap标签（resultMap="BaseResultMap"），因此先定义resultMap标签
> 这个有问题，也必须手动加上 resultMap="BaseResultMap" 才行

最新的提交尝试一下，看看
