### ISSUE TITLE
是否可以考虑通过struct生成xml时，另外给struct增加一个tag

### ISSUE THREAD

**Issue by guotie** [zhuxiujia/GoMybatis#39]
目前是使用json这个tag来生成xml，这样的话，不是很灵活，建议另外使用一个tag来生成xml

**Comment by zhuxiujia** [comment]
> 目前是使用json这个tag来生成xml，这样的话，不是很灵活，建议另外使用一个tag来生成xml

目前只使用json(Tag)+gm(Tag) 2种tag生成xml
其中json tag 会在序列化和反序列化使用。
gm tag只在生成xml 的过程使用，gm tag 只是指定 表id，版本号字段，逻辑删除字段 用。
