### ISSUE TITLE
xml中的where标签功能是否有效

### ISSUE THREAD

**Issue by Arvinxiaoxu** [zhuxiujia/GoMybatis#4]
这个<where>标签的功能是不还没有开发呀，控制输出信息
panic: [GoMybatis] find not support element! where

**Comment by zhuxiujia** [comment]
where 标签很快就会支持，暂时可写 sql wher 加 and or 代替

**Comment by zhuxiujia** [comment]
> > where 标签很快就会支持，暂时可写 sql where 加 and or 代替
> 
> 嗯嗯

<where>标签已支持，查看/example文件夹

**Comment by Arvinxiaoxu** [comment]
> > > where 标签很快就会支持，暂时可写 sql where 加 and or 代替
> > 
> > 
> > 嗯嗯
> 
> 标签已支持，查看/example文件夹

已测试成功
