### ISSUE TITLE
select 无法得到数据

### ISSUE THREAD

**Issue by guotie** [zhuxiujia/GoMybatis#40]
update insert都正常，select的sql语句也没问题

**Comment by guotie** [comment]
我靠，自动生成的xml的 property 为什么是小写开头？

就是这个导致没法找到对应的field

**Comment by guotie** [comment]
感觉驼峰命名有很多问题

**Comment by guotie** [comment]
原来是xml没有加 ` resultMap="BaseResultMap"`  例子里也有好几个select没加，真的可以运行吗

**Comment by zhuxiujia** [comment]
> 原来是xml没有加 ` resultMap="BaseResultMap"` 例子里也有好几个select没加，真的可以运行吗

之前的版本支持 依靠json解析，所以可以不写。目前解析依靠resultmap，这块目前还在整改。

**Comment by guotie** [comment]
很赞的项目，感谢作者

**Comment by zhuxiujia** [comment]
> 很赞的项目，感谢作者

刚刚回复的有问题，最新版本的提交，是依靠resultMap+json来反序列化查询结果的。和老版本一样

> 我靠，自动生成的xml的 property 为什么是小写开头？
> 
> 就是这个导致没法找到对应的field

自动生成的xml是否存在问题？

**Comment by zhuxiujia** [comment]
> 我靠，自动生成的xml的 property 为什么是小写开头？
> 
> 就是这个导致没法找到对应的field

自动生成的字段取了json的字段了，这个问题已得到修复，可以check 最新的提交
