### ISSUE TITLE
select的返回，update的参数为什么不能是指针？

### ISSUE THREAD

**Issue by guotie** [zhuxiujia/GoMybatis#41]
用结构体不是需要增加一次copy，影响效率吗

**Comment by zhuxiujia** [comment]
> 用结构体不是需要增加一次copy，影响效率吗

真正影响效率的是IO，参数可以接收指针的，没有说一定要结构体。

**Comment by guotie** [comment]
insert update传指针好像没法取到内容；

select的结果不能为ptr，interface{}

**Comment by zhuxiujia** [comment]
> insert update传指针好像没法取到内容；
> 
> select的结果不能为ptr，interface{}

问题2：select的结果不能为ptr，interface{} 。
ptr 是个指针，那么它在哪初始化呢？
interface{} 结果是无意义的，当然不能支持

**Comment by zhuxiujia** [comment]
> insert update传指针好像没法取到内容；
> 
> select的结果不能为ptr，interface{}

insert update传指针好像没法取到内容；
这部分的具体代码发一下
