### ISSUE TITLE
sql查询结果解码相关问题

### ISSUE THREAD

**Issue by dxwy2001** [zhuxiujia/GoMybatis#43]
Decode方法中如果struct 的json tag 跟数据表的字段定义不一致会无法导出

**Comment by zhuxiujia** [comment]
> Decode方法中如果struct 的json tag 跟数据表的字段定义不一致会无法导出

试试最新的版本

**Comment by zhuxiujia** [comment]
> Decode方法中如果struct 的json tag 跟数据表的字段定义不一致会无法导出

GoMybatis 本身就规定json tag 必须和表字段一抹一样，比如json是  del_flag  那么表字段也是
