### ISSUE TITLE
建议开发时，日志里面不输出DecoderTemplete

### ISSUE THREAD

**Issue by wzhsh90** [zhuxiujia/GoMybatis#44]
1、当xml多了，DecoderTemplete 显示太多了，建议去掉

2、warning ======================== mapper.InsertTemplete() have not define tag mapperParams:"",maybe can not get param value! 这种日志也是交意义的建议去掉

3、对模板sql 建议是直接生成sql 文件在xml ,而不是只使用标签，只使用标签不灵活，尤其是做update

自己有空写个小项目，使用这个项目到开发，你会发现有些地方使用起来有点不方便。

**Comment by zhuxiujia** [comment]
> 1、当xml多了，DecoderTemplete 显示太多了，建议去掉
> 
> 2、warning ======================== mapper.InsertTemplete() have not define tag mapperParams:"",maybe can not get param value! 这种日志也是交意义的建议去掉
> 
> 3、对模板sql 建议是直接生成sql 文件在xml ,而不是只使用标签，只使用标签不灵活，尤其是做update
> 
> 自己有空写个小项目，使用这个项目到开发，你会发现有些地方使用起来有点不方便。

*  DecoderTemplete 打印的都是它生成的xml，而且是动态生成的，所以要打印。
warning会使用反射在程序启动前执行必要的规则检查，但是难免会扫描到templete（templete其实可以省略param tag的）这里。
因此我不太同意禁用警告

* 同时也不应该屏蔽自动生成的xml
因为很多框架很喜欢使用go generate生成静态代码，我认为静态代码维护困难，而且既不安全。
gomybatis比其他go框架先进的地方其实就使用反射+闭包 极大的简化了开发者的构建流程
（因为你有必要观察是否按照你的预期自动构建了xml，以及逻辑是否正确，否则出了错误都不知道哪里的错）

**Comment by zhuxiujia** [comment]
> 1、当xml多了，DecoderTemplete 显示太多了，建议去掉
> 
> 2、warning ======================== mapper.InsertTemplete() have not define tag mapperParams:"",maybe can not get param value! 这种日志也是交意义的建议去掉
> 
> 3、对模板sql 建议是直接生成sql 文件在xml ,而不是只使用标签，只使用标签不灵活，尤其是做update
> 
> 自己有空写个小项目，使用这个项目到开发，你会发现有些地方使用起来有点不方便。

另外自己在 去年早已应用到生产环境，基本线上0 bug. 应付一般应用绰绰有余

**Comment by wzhsh90** [comment]
设计是多元素的，你说的也是有道理

1、针对decodeTemplate 日志，我还是希望能再加一个动态日志控制，是否打印动态解析日志，如：dynamicSqlLog: true,默认true，开发人员可以自己控制，真不想看到一大堆日志打印出来
