### ISSUE TITLE
查询结果不能映射到有继承的对象

### ISSUE THREAD

**Issue by wzhsh90** [zhuxiujia/GoMybatis#46]
type A struct {
BaseMoney    string `json:"base_money"`
}
type B struct {
A
Test    string `json:"test"`
}
sql 返回B，但数据不会映射A中字段，请问这样的如何处理。

**Comment by zhuxiujia** [comment]
> type A struct {
> BaseMoney string `json:"base_money"`
> }
> type B struct {
> A
> Test string `json:"test"`
> }
> sql 返回B，但数据不会映射A中字段，请问这样的如何处理。

是的，目前框架只有一个单层struct反射解析器，依靠反射能快速反序列化。这也是框架性能高的原因（多层扫描反射势必导致性能低下（可以参考json 反序列化））
因为mysql之类的表结构基本都是单层结构（也只有mongodb之类的nosql数据库有多层复合结构的），建议使用当个struct对象而不是继承对象。
