### ISSUE TITLE
PostgreSQL预处理问题

### ISSUE THREAD

**Issue by flytreeleft** [zhuxiujia/GoMybatis#47]
PostgreSQL预处理的占位符应该是`$1`、`$2`这种，不是`?`，[这里](http://go-database-sql.org/prepared.html#parameter-placeholder-syntax)有说明，所以，GoMybatis是否需要为此做针对性处理呢？

**Comment by zhuxiujia** [comment]
> PostgreSQL预处理的占位符应该是`$1`、`$2`这种，不是`?`，[这里](http://go-database-sql.org/prepared.html#parameter-placeholder-syntax)有说明，所以，GoMybatis是否需要为此做针对性处理呢？

6.2.0已加入支持
感谢关注
