### ISSUE TITLE
在使用过程中发现max_prepared_stmt_count 问题

### ISSUE THREAD

**Issue by fghosth** [zhuxiujia/GoMybatis#48]
mysql Com_stmt_prepare值一直增加，没有close。导致max_prepared_stmt_count 超出问题。
能否修复一下这个问题，或者给我权限，我提交下修改过的代码。

**Comment by zhuxiujia** [comment]
> mysql Com_stmt_prepare值一直增加，没有close。导致max_prepared_stmt_count 超出问题。
> 能否修复一下这个问题，或者给我权限，我提交下修改过的代码。

恩，提交，记得跑一遍 go test 保障代码测试正常

**Comment by fghosth** [comment]
已经运行过go test . 我新建了一个hotfix/max_prepared_stmt 分支，但是没有权限提交。用户名fghosth@163.com

**Comment by zhuxiujia** [comment]
> 已经运行过go test . 我新建了一个hotfix/max_prepared_stmt 分支，但是没有权限提交。用户名[fghosth@163.com](mailto:fghosth@163.com)

git 提交到你自己的fghosth/GoMybatis  这个库master分支里，然后百度一下 github pull requests怎么用。

**Comment by fghosth** [comment]
我发起了一个 pull request。check 失败了。

The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.

我需要怎么做？

**Comment by zhuxiujia** [comment]
> 我发起了一个 pull request。check 失败了。
> 
> The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
> 
> 我需要怎么做？

这个后面在看看 咋解决吧，go test 跑通了，我这边已合并
