### ISSUE TITLE
在测试example中的CountByCondition 方法时，无法正常返回数据类型int

### ISSUE THREAD

**Issue by Arvinxiaoxu** [zhuxiujia/GoMybatis#5]
**方法：**
CountByCondition func(name string,age int)(int,error)	`mapperParams:"myName,myAge"`
**SQL:**
 <select id="CountByCondition">
        select count(id)
        from tb_user
        where 1=1
          <if test="myName !=''">
              and name like concat('%',#{myName},'%')
          </if>
          <if test="myAge >0">
              and age &gt;= #{myAge}
          </if>
    </select>
**控制报错信息：**
Decode result type only support slice and map
发出的sql语句是是正确的,请博主试一下

**Comment by zhuxiujia** [comment]
> **方法：**
> CountByCondition func(name string,age int)(int,error)	`mapperParams:"myName,myAge"`
> **SQL:**
> select count(id) from tb_user where 1=1 and name like concat('%',#{myName},'%') and age >= #{myAge} 
> **控制报错信息：**
> Decode result type only support slice and map
> 发出的sql语句是是正确的,请博主试一下

已修复，并增加了count()的测试，可以测试一下

**Comment by Arvinxiaoxu** [comment]
测试已经成功

**Comment by Arvinxiaoxu** [comment]
> > **方法：**
> > CountByCondition func(name string,age int)(int,error)	`mapperParams:"myName,myAge"`
> > **SQL:**
> > select count(id) from tb_user where 1=1 and name like concat('%',#{myName},'%') and age >= #{myAge}
> > **控制报错信息：**
> > Decode result type only support slice and map
> > 发出的sql语句是是正确的,请博主试一下
> 
> 已修复，并增加了count()的测试，可以测试一下

测试已成功
