### ISSUE TITLE
关于order by的问题

### ISSUE THREAD

**Issue by fghosth** [zhuxiujia/GoMybatis#51]
xml文件中： 
1. order by id desc 
2. <if test="orders != '' ">order by #{orders}</if>
以上两种用法生成的日志都包含『order by』部分，但是第一种排序生效，第二种没有生效。
求助：是什么问题？应该怎么解决

**Comment by zhuxiujia** [comment]
> xml文件中：
> 
> 1. order by id desc
> 2. order by #{orders}
>    以上两种用法生成的日志都包含『order by』部分，但是第一种排序生效，第二种没有生效。
>    求助：是什么问题？应该怎么解决

orders  这个参数传进来了吗？函数注解加了吗？  args：”orders“

**Comment by fghosth** [comment]
加了。我在源码里面插入了调试代码。
localSession.go 350行插入了fmt.Println(sqlPrepare, args),发现build的sql语句，和args都正确。但是输出的结果，顺序不正确。

**Comment by zhuxiujia** [comment]
> 加了。我在源码里面插入了调试代码。
> localSession.go 350行插入了fmt.Println(sqlPrepare, args),发现build的sql语句，和args都正确。但是输出的结果，顺序不正确。

xml 代码贴上来看看

**Comment by fghosth** [comment]
<select id="SelectByCondition" resultMap="BaseResultMap">
	select * from reports
	<where>
		<if test="countTypeID != 0">and count_type_id = #{countTypeID}</if>
		<if test="countType != 0">and count_type = #{countType}</if>
		<if test="partnerID != 0">and partner_id = #{partnerID}</if>
	</where>
    order by id desc
	<if test="orders != '' ">order by #{orders}</if>
	<if test="limit != 0">limit #{offset}, #{limit}</if>
</select>

**Comment by fghosth** [comment]
1:[使用order by #{orders}的日志](https://fghosth.github.io/images/r1.png)
2：[直接写 order by id desc的日志](https://fghosth.github.io/images/r2.png)

有颜色的部分是加载框架源码文件 localSession.go 350  【sqlPrepare, args】参数的输出

**Comment by zhuxiujia** [comment]
> 1: [使用order by #{orders}的日志](https://fghosth.github.io/images/r1.png)
> 2: [直接写 order by id desc的日志](https://fghosth.github.io/images/r2.png)
> 
> 有颜色的部分是加载框架源码文件 localSession.go 350 【sqlPrepare, args】参数的输出
> 
> 两种方式数据结果顺序不同。

你把 gopath 目录下或者 go mod 的依赖 都清理下，然后重新下载这个库。 我本地是正常的，可能你用的是老版本
