### ISSUE TITLE
select sql resultMap 不起作用

### ISSUE THREAD

**Issue by wzhsh90** [zhuxiujia/GoMybatis#52]
<result column="dic_name" property="HonorLevelName" langType="string"/>

这个dic_name是有值的，model里面有字段为HonorLevelName,数据不能映射上去，
但把HonorLevelName 属性修改为DicName就正常了

猜测：查询得到数据没有根据resultMap 来处理，我用的v6.2.3+incompatible

我的微信：1521510339，有空加我

**Comment by zhuxiujia** [comment]
> 这个dic_name是有值的，model里面有字段为HonorLevelName,数据不能映射上去，
> 但把HonorLevelName 属性修改为DicName就正常了
> 
> 猜测：查询得到数据没有根据resultMap 来处理，我用的v6.2.3+incompatible
> 
> 我的微信：1521510339，有空加我

代码贴上来看看

**Comment by wzhsh90** [comment]
1、  <result column="dic_name" property="HonorLevelName" langType="string"/>
type HonorOrg struct {
	HonorLevelName string `json:"honor_level_name"`
}
这样写不行

2、建议把warning 也做成可控制的

ram value!
2020/04/30 16:30:50 [GoMybatis] warning ======================== agemapper.InsertTemplete() have not define tag args:"",maybe can
not get param value!
2020/04/30 16:30:50 [GoMybatis] warning ======================== agemapper.Update() have not define tag args:"",maybe can not get
param value!
2020/04/30 16:30:50 [GoMybatis] warning ======================== agemapper.InsertTemplete() have not define tag args:"",maybe can
not get param value!
2020/04/30 16:30:50 [GoMybatis] warning ======================== agemapper.InsertTempleteBatch() have not define tag args:"",maybe
 can not get param value!
2020/04/30 16:30:50 [GoMybatis] warning ======================== agemapper.Update() have not define tag args:"",maybe can not get
param value!
2020/04/30 16:30:50 [GoMybatis] warning ======================== classmapper.InsertTemplete() have not define tag args:"",maybe ca
n not get param value!
2020/04/30 16:30:50 [GoMybatis] warning ======================== classmapper.Update() have not define tag args:"",maybe can not ge
t param value!

一堆这个，没有什么意义
