### ISSUE TITLE
在使用postgres数据时出现错

### ISSUE THREAD

**Issue by fghosth** [zhuxiujia/GoMybatis#53]
在使用postgres数据时出现错误：
发现错误见下图：
[源码截图](https://fghosth.github.io/images/myb_001.jpg)

**Comment by zhuxiujia** [comment]
> 在使用postgres数据时出现错误：
> 发现错误见下图：
> [源码截图](https://fghosth.github.io/images/myb_001.jpg)

这个模块没有在使用的，已删除了哈

**Comment by zhuxiujia** [comment]
> 在使用postgres数据时出现错误：
> 发现错误见下图：
> [源码截图](https://fghosth.github.io/images/myb_001.jpg)

估计是历史遗留的代码，已经把这个模块替换为go标准库的database/sql .Stmt 来准备预编译，官方库理论上没有任何问题

**Comment by zhuxiujia** [comment]
> > 在使用postgres数据时出现错误：
> > 发现错误见下图：
> > [源码截图](https://fghosth.github.io/images/myb_001.jpg)
> 
> 这个模块没有在使用的，已删除了哈

不应该删除这个模块，现在已重新提交。

> > 在使用postgres数据时出现错误：
> > 发现错误见下图：
> > [源码截图](https://fghosth.github.io/images/myb_001.jpg)
> 
> 这个模块没有在使用的，已删除了哈

这个模块恢复了，并且6.2.4版本上做了修复

**Comment by Xxf123abc** [comment]
pg使用where 这种子标签 占位符拼接的错误

**Comment by Xxf123abc** [comment]
而且 property在内嵌结构体上时 参数就取不到

**Comment by zhuxiujia** [comment]
> 而且 property在内嵌结构体上时 参数就取不到

结构体，首字母必须大写，否则go的权限不足以访问写入值的.
另外问下 pg 环境下这个问题解决了吗？

**Comment by Xxf123abc** [comment]
> > 而且 property在内嵌结构体上时 参数就取不到
> 
> 结构体，首字母必须大写，否则go的权限不足以访问写入值的.
> 另外问下 pg 环境下这个问题解决了吗？

跟访问权限没关系 我debug进去看了 是golang reflect 的时候只取了第一层结构体的值 如果要访问嵌入的结构体需要显示指明
pg的问题 我昨晚给你提了pr 合进去以后解决了

**Comment by zhuxiujia** [comment]
> > > 而且 property在内嵌结构体上时 参数就取不到
> > 
> > 
> > 结构体，首字母必须大写，否则go的权限不足以访问写入值的.
> > 另外问下 pg 环境下这个问题解决了吗？
> 
> 跟访问权限没关系 我debug进去看了 是golang reflect 的时候只取了第一层结构体的值 如果要访问嵌入的结构体需要显示指明
> pg的问题 我昨晚给你提了pr 合进去以后解决了

是不是用了pg的json结构？之前的设计是反射第一层然后设置值的。

**Comment by Xxf123abc** [comment]
> > > > 而且 property在内嵌结构体上时 参数就取不到
> > > 
> > > 
> > > 结构体，首字母必须大写，否则go的权限不足以访问写入值的.
> > > 另外问下 pg 环境下这个问题解决了吗？
> > 
> > 
> > 跟访问权限没关系 我debug进去看了 是golang reflect 的时候只取了第一层结构体的值 如果要访问嵌入的结构体需要显示指明
> > pg的问题 我昨晚给你提了pr 合进去以后解决了
> 
> 是不是用了pg的json结构？之前的设计是反射第一层然后设置值的。

eg: type struct Base {
        Name 
}
type struct Model {
   Base 
}
after reflect if we want  to get Name property  should use Model.Base.Name

**Comment by Xxf123abc** [comment]
> > > > 而且 property在内嵌结构体上时 参数就取不到
> > > 
> > > 
> > > 结构体，首字母必须大写，否则go的权限不足以访问写入值的.
> > > 另外问下 pg 环境下这个问题解决了吗？
> > 
> > 
> > 跟访问权限没关系 我debug进去看了 是golang reflect 的时候只取了第一层结构体的值 如果要访问嵌入的结构体需要显示指明
> > pg的问题 我昨晚给你提了pr 合进去以后解决了
> 
> 是不是用了pg的json结构？之前的设计是反射第一层然后设置值的。

golang的反射  我用的不多 不是特别了解  这个issue 你关了吧

**Comment by zhuxiujia** [comment]
> > > > > 而且 property在内嵌结构体上时 参数就取不到
> > > > 
> > > > 
> > > > 结构体，首字母必须大写，否则go的权限不足以访问写入值的.
> > > > 另外问下 pg 环境下这个问题解决了吗？
> > > 
> > > 
> > > 跟访问权限没关系 我debug进去看了 是golang reflect 的时候只取了第一层结构体的值 如果要访问嵌入的结构体需要显示指明
> > > pg的问题 我昨晚给你提了pr 合进去以后解决了
> > 
> > 
> > 是不是用了pg的json结构？之前的设计是反射第一层然后设置值的。
> 
> golang的反射 我用的不多 不是特别了解 这个issue 你关了吧

嗯嗯，理论上来说，sql 都是返回只有一层的，例如mysql  返回 （id,name,age,password.....）等等
