### ISSUE TITLE
Error 1390: Prepared stat ement contains too many placeholders

### ISSUE THREAD

**Issue by wzhsh90** [zhuxiujia/GoMybatis#56]
一次性导入太多就会报错

**Comment by wzhsh90** [comment]
导入数据500*11列，好慢，如果数据再大点就更慢

**Comment by zhuxiujia** [comment]
> 一次性导入太多就会报错

导入什么数据？
一般来说 prepared statement sql的长度不能太大的

**Comment by wzhsh90** [comment]
现在还是千多条数据，太多了就不得行

**Comment by zhuxiujia** [comment]
> 现在还是千多条数据，太多了就不得行

我记得mysql 的sql长度不能超过1MB，还是多少来着，注意控制批量长度就行
