### ISSUE TITLE
<where> bug

### ISSUE THREAD

**Issue by wzhsh90** [zhuxiujia/GoMybatis#58]
SELECT
        <include refid="base_col"/>
        FROM sys_role_info_t
        <where>
            <if test="name!=''">and role_name like #{name}</if>
        </where>

name==""时，生成的sql 为
select   <include refid="base_col"/>
        FROM sys_role_info_t where

**Comment by zhuxiujia** [comment]
> SELECT
> 
> FROM sys_role_info_t
> 
> and role_name like #{name}
> name==""时，生成的sql 为
> select
> FROM sys_role_info_t where

哪个版本,具体代码贴一下

**Comment by wzhsh90** [comment]
v6.2.3

**Comment by zhuxiujia** [comment]
> v6.2.3

用最新版本再试试

**Comment by wzhsh90** [comment]
我用最新版本6.3.2一样存在这个bug 
<where>
            <if test="state!=-1">
                and state=#{state}
            </if>
            <if test="name!=''">
                and title like #{name}
            </if>
        </where>
当所有条件都不满足时，不应该生成一个where 

java:
where标签的作用：如果该标签包含的元素中有返回值，就插入一个where；如果where后面的字符串是以and或or开头的，就将它们剔除。

**Comment by zhuxiujia** [comment]
> 我用最新版本6.3.2一样存在这个bug
> 
> 
> and state=#{state}
> 
> 
> and title like #{name}
> 
> 
> 当所有条件都不满足时，不应该生成一个where
> 
> java:
> where标签的作用：如果该标签包含的元素中有返回值，就插入一个where；如果where后面的字符串是以and或or开头的，就将它们剔除。

v6.3.3版本修复了这个问题，当where标签body没有条件满足（也就是包含的sql是空字符串）的时候，where关键字 不写入

**Comment by wzhsh90** [comment]
新bug又来了

error == invalid character 'f' in exponent of numeric literal

兄弟，你要多测试呀，不然我们会进坑的

**Comment by wzhsh90** [comment]
你应该修改到什么地方了，原来的程序都有问题了
 error == invalid character 'w' after object key:value pair

**Comment by zhuxiujia** [comment]
> 你应该修改到什么地方了，原来的程序都有问题了
> error == invalid character 'w' after object key:value pair

json解码有bug，已经修复修复在了v6.3.5

**Comment by wzhsh90** [comment]
6.3.5 还是存在bug
 error == invalid character 'f' in exponent of numeric literal

大兄弟，你测试了么？

**Comment by zhuxiujia** [comment]
> 6.3.5 还是存在bug
> error == invalid character 'f' in exponent of numeric literal
> 
> 大兄弟，你测试了么？

测试用例跑完才发布的，你这个错误应该检查一下，代码

**Comment by wzhsh90** [comment]
你再检查一下程序，这个应该还是版本有bug引起的，我换回旧版本就没这个问题



---Original---

**Comment by zhuxiujia** [comment]
> 你再检查一下程序，这个应该还是版本有bug引起的，我换回旧版本就没这个问题
> […](#)
> ---Original--- From: "zxj"<notifications@github.com&gt; Date: Mon, Jun 29, 2020 20:58 PM To: "zhuxiujia/GoMybatis"<GoMybatis@noreply.github.com&gt;; Cc: "wzhsh90"<624837932@qq.com&gt;;"Author"<author@noreply.github.com&gt;; Subject: Re: [zhuxiujia/GoMybatis] <where&gt; bug (#58) 6.3.5 还是存在bug error == invalid character 'f' in exponent of numeric literal 大兄弟，你测试了么？ 测试用例跑完才发布的，你这个错误应该检查一下，代码 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

把报错位置的代码贴上来哈，example包里面的代码目前一切正常

**Comment by wzhsh90** [comment]
![1xxx](https://user-images.githubusercontent.com/16187191/86081176-4a896d00-bac7-11ea-8077-2618feadf272.png)

**Comment by wzhsh90** [comment]
11:44:54 app         | 2020/06/30 11:44:54 [GoMybatis] [90152de2-e746-42d6-9257-78702eec8e7c] Query ==>  select         count(*)
       from notice_t
11:44:54 app         | 2020/06/30 11:44:54 [GoMybatis] [90152de2-e746-42d6-9257-78702eec8e7c] Args  ==> []
2020/06/30 11:44:54 [GoMybatis] [90152de2-e746-42d6-9257-78702eec8e7c] Close session
2020/06/30 11:44:54 [GoMybatis] [90152de2-e746-42d6-9257-78702eec8e7c] ReturnRows <== 1
2020/06/30 11:44:54 [GoMybatis] [85bdf2ea-1753-4607-8421-de94aec6a2c6] Query ==>  select id,title,content,create_time ,state ,show
_seq ,browser_cnt,end_time from notice_t order by create_time desc         limit  ? , ?
2020/06/30 11:44:54 [GoMybatis] [85bdf2ea-1753-4607-8421-de94aec6a2c6] Args  ==> [0,20]
2020/06/30 11:44:54 [GoMybatis] [85bdf2ea-1753-4607-8421-de94aec6a2c6] ReturnRows <== 0
2020/06/30 11:44:54 [GoMybatis] [85bdf2ea-1753-4607-8421-de94aec6a2c6] error == invalid character 'f' in exponent of numeric liter
al
2020/06/30 11:44:54 [GoMybatis] [85bdf2ea-1753-4607-8421-de94aec6a2c6] Close session

**Comment by wzhsh90** [comment]
15215109339 我微信，加微信处理吧
