### ISSUE TITLE
&lt字符不能被正确解析

### ISSUE THREAD

**Issue by Arvinxiaoxu** [zhuxiujia/GoMybatis#6]
**错误信息：**
unescaped < inside quoted string
请博主试一下

**Comment by zhuxiujia** [comment]
> **错误信息：**
> unescaped < inside quoted string
> 请博主试一下

/example/Example_ActivityMapper.xml 中, <if test="endTime != ''">and create_time &lt;= #{endTime}</if>是正常解析的，不知道你代码怎么写的

**Comment by xvpenghao** [comment]
**sql:**
```
    <select id="Choose" resultMap="userResultMap">
        select id,name,age
        from tb_user
        <choose>
            <when test="age==24">where age = 24</when>
             <when test="age < 24">where age &lt; 24</when>
            <otherwise>where age > #{age}</otherwise>
        </choose>
    </select>
```
**执行函数**
Choose func(age int)([]User,error)	`mapperParams:"age"`
**错误信息**
panic: XML syntax error on line 33: unescaped < inside quoted string

**Comment by zhuxiujia** [comment]
> **sql:**
> 
> ```
>     <select id="Choose" resultMap="userResultMap">
>         select id,name,age
>         from tb_user
>         <choose>
>             <when test="age==24">where age = 24</when>
>              <when test="age < 24">where age &lt; 24</when>
>             <otherwise>where age > #{age}</otherwise>
>         </choose>
>     </select>
> ```
> **执行函数**
> Choose func(age int)([]User,error)	`mapperParams:"age"`
> **错误信息**
> panic: XML syntax error on line 33: unescaped < inside quoted string

表达式里面 这个符号是在xml加载的时候无法被解析，已经提交issues 到 etree这个框架的作者那老外那里了，看他咋解决，他解决了咋们这边更新

**Comment by zhuxiujia** [comment]
> **sql:**
> 
> ```
>     <select id="Choose" resultMap="userResultMap">
>         select id,name,age
>         from tb_user
>         <choose>
>             <when test="age==24">where age = 24</when>
>              <when test="age < 24">where age &lt; 24</when>
>             <otherwise>where age > #{age}</otherwise>
>         </choose>
>     </select>
> ```
> **执行函数**
> Choose func(age int)([]User,error)	`mapperParams:"age"`
> **错误信息**
> panic: XML syntax error on line 33: unescaped < inside quoted string

佬外没解决签，其实你可以先使用 ```&lt;``` 代替 <

**Comment by zhuxiujia** [comment]
> **sql:**
> 
> ```
>     <select id="Choose" resultMap="userResultMap">
>         select id,name,age
>         from tb_user
>         <choose>
>             <when test="age==24">where age = 24</when>
>              <when test="age < 24">where age &lt; 24</when>
>             <otherwise>where age > #{age}</otherwise>
>         </choose>
>     </select>
> ```
> **执行函数**
> Choose func(age int)([]User,error)	`mapperParams:"age"`
> **错误信息**
> panic: XML syntax error on line 33: unescaped < inside quoted string

已经添加了补丁临时解决test表达式无法解析符号 ‘&lt;’的问题，最终还得etree框架作者处理issues
