### ISSUE TITLE
有一对多映射功能吗？

### ISSUE THREAD

**Issue by LczFrist** [zhuxiujia/GoMybatis#61]

**Comment by zhuxiujia** [comment]
写对应sql，和对应的结构体即可

**Comment by LczFrist** [comment]
不是很懂，需要在xml文件里面去配置什么吗？比如我一个结构体里面是一些普通的字段和一个结构体切片，和Java中mybatis的用法一样吗？

**Comment by LczFrist** [comment]
> 写对应sql，和对应的结构体即可
不是很懂，需要在xml文件里面去配置什么吗？比如我一个结构体里面是一些普通的字段和一个结构体切片，和Java中mybatis的用法一样吗

**Comment by LczFrist** [comment]
> 写对应sql，和对应的结构体即可



> 写对应sql，和对应的结构体即可


不是很懂，需要在xml文件里面去配置什么吗？比如我一个结构体里面是一些普通的字段和一个结构体切片，和Java中mybatis的用法一样吗

**Comment by zhuxiujia** [comment]
> 不是很懂，需要在xml文件里面去配置什么吗？比如我一个结构体里面是一些普通的字段和一个结构体切片，和Java中mybatis的用法一样吗？

是用json解析映射结果的，select 关联查询出来的结构能解析json就行

**Comment by LczFrist** [comment]
> > 不是很懂，需要在xml文件里面去配置什么吗？比如我一个结构体里面是一些普通的字段和一个结构体切片，和Java中mybatis的用法一样吗？
> 
> 是用json解析映射结果的，select 关联查询出来的结构能解析json就行

![image](https://user-images.githubusercontent.com/56995010/101275198-b9899100-37de-11eb-9d4e-2f176c893dc0.png)
![image](https://user-images.githubusercontent.com/56995010/101275213-e5a51200-37de-11eb-821e-f977bac394de.png)
![image](https://user-images.githubusercontent.com/56995010/101275230-05d4d100-37df-11eb-8497-a105b7620138.png)

![image](https://user-images.githubusercontent.com/56995010/101275225-f3f32e00-37de-11eb-9302-b83c0fb9378a.png)
是哪里写的不对吗？麻烦作者指导一下

**Comment by zhuxiujia** [comment]
比如select  a as a, b  as b from table.  只要mapper定义的方法返回的结构体包含 struct{  a string , b string}就行了啊

**Comment by LczFrist** [comment]
外面是一个结构体，是单个实例，实例里面有一个切片，查出来多条数据并没有给解析到切片里面去啊，错误提示的很明确了，size > 1

**Comment by zhuxiujia** [comment]
size > 1 说明你返回了数组，但是解析的结构体又是单个

**Comment by LczFrist** [comment]
对，是单个，但是单个里面包含了一个数组，所以我问有没有一对多或多对多的映射功能啊

**Comment by zhuxiujia** [comment]
> 对，是单个，但是单个里面包含了一个数组，所以我问有没有一对多或多对多的映射功能啊

返回的结构改成 []struct 也就是返回的结构定义改成数组呀

**Comment by LczFrist** [comment]
![image](https://user-images.githubusercontent.com/56995010/101275905-4d119080-37e4-11eb-9346-217a7d7a1a82.png)


就我想返回这样的数据结构，不需要额外用代码做转换，一条sql就能搞定的，不知道可以实现吗？我觉得大概是我没理解你的意思：）

**Comment by zhuxiujia** [comment]
> ![image](https://user-images.githubusercontent.com/56995010/101275905-4d119080-37e4-11eb-9346-217a7d7a1a82.png)
> 
> 就我想返回这样的数据结构，不需要额外用代码做转换，一条sql就能搞定的，不知道可以实现吗？我觉得大概是我没理解你的意思：）


select *  from table 返回的数据都是一列一列返回的，能返回数组的估计只有PG这个数据库。
如果要在单个结构体里面再包含数组的话，前提是 select *  from table 中返回其中一列的数据   有数组存在

**Comment by LczFrist** [comment]
![image](https://user-images.githubusercontent.com/56995010/101276100-c1006880-37e5-11eb-8209-22a7904abea3.png)

就这种功能

**Comment by zhuxiujia** [comment]
> ![image](https://user-images.githubusercontent.com/56995010/101276100-c1006880-37e5-11eb-8209-22a7904abea3.png)
> 
> 就这种功能

嗯嗯，解决了的话，我要关闭这个问题了

**Comment by LczFrist** [comment]
没解决呀，到底是我不理解你说的，还是你不理解我说的？都无语了，算了

**Comment by zhuxiujia** [comment]
> 没解决呀，到底是我不理解你说的，还是你不理解我说的？都无语了，算了

你的图片显示不出来

**Comment by LczFrist** [comment]
不是啊，一对多多对多映射配置你不懂吗？我问的是有没有这个功能啊，就mybatis里面的collection啊

**Comment by zhuxiujia** [comment]
> 不是啊，一对多多对多映射配置你不懂吗？我问的是有没有这个功能啊，就mybatis里面的collection啊

一对多多对多，要定义组合的结构体，比如查struct A{ id int , name string}  和structB{ id int , age  int}
那么你要定义一个组合结构体 struct AB {A,B } 或者一个map 不就解析出来了么，
你不会用json 吗？

**Comment by zohar-soul** [comment]
现在一对多映射支持了嘛?
@zhuxiujia

**Comment by bmmpp** [comment]
> 



> 现在一对多映射支持了嘛? @zhuxiujia

mybatis 的魅力不是 原生sql 吗， 为什么要关注 类似 collectoin 的设计？
